<?php

namespace Enesdayanc\MasterpassGenerateKey;

/**
 * Class which returns the class map definition
 * @package
 */
class ClassMap
{
    /**
     * Returns the mapping between the WSDL Structs and generated Structs' classes
     * This array is sent to the \SoapClient when calling the WS
     * @return string[]
     */
    final public static function get()
    {
        return array(
            'GenerateKey' => '\\Enesdayanc\\MasterpassGenerateKey\\StructType\\GenerateKey',
            'GenerateKeyResponse' => '\\Enesdayanc\\MasterpassGenerateKey\\StructType\\GenerateKeyResponse',
            'GenerateKeyRequest' => '\\Enesdayanc\\MasterpassGenerateKey\\StructType\\GenerateKeyRequest',
            'GenerateKeyRequestBody' => '\\Enesdayanc\\MasterpassGenerateKey\\StructType\\GenerateKeyRequestBody',
            'GenerateKeyAdditionalFields' => '\\Enesdayanc\\MasterpassGenerateKey\\StructType\\GenerateKeyAdditionalFields',
            'GenerateKeyResult' => '\\Enesdayanc\\MasterpassGenerateKey\\StructType\\GenerateKeyResult',
            'GenerateKeyResponseBody' => '\\Enesdayanc\\MasterpassGenerateKey\\StructType\\GenerateKeyResponseBody',
            'RequestHeader' => '\\Enesdayanc\\MasterpassGenerateKey\\StructType\\RequestHeader',
            'CustomField' => '\\Enesdayanc\\MasterpassGenerateKey\\StructType\\CustomField',
            'ResponseHeader' => '\\Enesdayanc\\MasterpassGenerateKey\\StructType\\ResponseHeader',
            'ResponseBody' => '\\Enesdayanc\\MasterpassGenerateKey\\StructType\\ResponseBody',
            'SmsNotification' => '\\Enesdayanc\\MasterpassGenerateKey\\StructType\\SmsNotification',
            'MoneySendResponseBody' => '\\Enesdayanc\\MasterpassGenerateKey\\StructType\\MoneySendResponseBody',
            'MerchantFinancialResponseBody' => '\\Enesdayanc\\MasterpassGenerateKey\\StructType\\MerchantFinancialResponseBody',
            'ConsumerRewardResponseBody' => '\\Enesdayanc\\MasterpassGenerateKey\\StructType\\ConsumerRewardResponseBody',
            'ArrayOfRewardList' => '\\Enesdayanc\\MasterpassGenerateKey\\ArrayType\\ArrayOfRewardList',
            'RewardList' => '\\Enesdayanc\\MasterpassGenerateKey\\StructType\\RewardList',
            'ArrayOfChequeList' => '\\Enesdayanc\\MasterpassGenerateKey\\ArrayType\\ArrayOfChequeList',
            'ChequeList' => '\\Enesdayanc\\MasterpassGenerateKey\\StructType\\ChequeList',
            'ConsumerFinancialResponseBody' => '\\Enesdayanc\\MasterpassGenerateKey\\StructType\\ConsumerFinancialResponseBody',
            'MasterPassResponseCustomField' => '\\Enesdayanc\\MasterpassGenerateKey\\StructType\\MasterPassResponseCustomField',
            'ArrayOfListItem' => '\\Enesdayanc\\MasterpassGenerateKey\\ArrayType\\ArrayOfListItem',
            'ListItem' => '\\Enesdayanc\\MasterpassGenerateKey\\StructType\\ListItem',
            'AdditionalFields' => '\\Enesdayanc\\MasterpassGenerateKey\\StructType\\AdditionalFields',
            'CustomRewardResponseBody' => '\\Enesdayanc\\MasterpassGenerateKey\\StructType\\CustomRewardResponseBody',
            'RewardResponseBody' => '\\Enesdayanc\\MasterpassGenerateKey\\StructType\\RewardResponseBody',
            'CommitPurchaseResponseBody' => '\\Enesdayanc\\MasterpassGenerateKey\\StructType\\CommitPurchaseResponseBody',
            'CustomCommitPurchaseResponseBody' => '\\Enesdayanc\\MasterpassGenerateKey\\StructType\\CustomCommitPurchaseResponseBody',
            'ProcessPaymentResponseBody' => '\\Enesdayanc\\MasterpassGenerateKey\\StructType\\ProcessPaymentResponseBody',
            'PurchaseAndRegisterResponseBody' => '\\Enesdayanc\\MasterpassGenerateKey\\StructType\\PurchaseAndRegisterResponseBody',
            'CustomRemotePurchaseResponseBody' => '\\Enesdayanc\\MasterpassGenerateKey\\StructType\\CustomRemotePurchaseResponseBody',
            'DirectPurchaseResponseBody' => '\\Enesdayanc\\MasterpassGenerateKey\\StructType\\DirectPurchaseResponseBody',
            'OtherMerchantResponseBody' => '\\Enesdayanc\\MasterpassGenerateKey\\StructType\\OtherMerchantResponseBody',
            'ReversePurchaseResponseBody' => '\\Enesdayanc\\MasterpassGenerateKey\\StructType\\ReversePurchaseResponseBody',
            'DirectPurchaseResponseBody3DAuth' => '\\Enesdayanc\\MasterpassGenerateKey\\StructType\\DirectPurchaseResponseBody3DAuth',
            'CustomCommitRecurringPaymentResponseBody' => '\\Enesdayanc\\MasterpassGenerateKey\\StructType\\CustomCommitRecurringPaymentResponseBody',
            'CommitRecurringPaymentResponseBody' => '\\Enesdayanc\\MasterpassGenerateKey\\StructType\\CommitRecurringPaymentResponseBody',
            'ManageRecurringPaymentResponseBody' => '\\Enesdayanc\\MasterpassGenerateKey\\StructType\\ManageRecurringPaymentResponseBody',
            'MaintainListResponseBody' => '\\Enesdayanc\\MasterpassGenerateKey\\StructType\\MaintainListResponseBody',
            'ViewListResponseBody' => '\\Enesdayanc\\MasterpassGenerateKey\\StructType\\ViewListResponseBody',
            'TransactionRefundResponseBody' => '\\Enesdayanc\\MasterpassGenerateKey\\StructType\\TransactionRefundResponseBody',
            'CustomTransactionRefundResponseBody' => '\\Enesdayanc\\MasterpassGenerateKey\\StructType\\CustomTransactionRefundResponseBody',
            'ViewMPListResponseBody' => '\\Enesdayanc\\MasterpassGenerateKey\\StructType\\ViewMPListResponseBody',
            'ArrayOfMPListItem' => '\\Enesdayanc\\MasterpassGenerateKey\\ArrayType\\ArrayOfMPListItem',
            'MPListItem' => '\\Enesdayanc\\MasterpassGenerateKey\\StructType\\MPListItem',
            'Card' => '\\Enesdayanc\\MasterpassGenerateKey\\StructType\\Card',
            'Contact' => '\\Enesdayanc\\MasterpassGenerateKey\\StructType\\Contact',
            'AddressListItem' => '\\Enesdayanc\\MasterpassGenerateKey\\StructType\\AddressListItem',
            'ViewAddressListResponseBody' => '\\Enesdayanc\\MasterpassGenerateKey\\StructType\\ViewAddressListResponseBody',
            'ArrayOfAddressListItem' => '\\Enesdayanc\\MasterpassGenerateKey\\ArrayType\\ArrayOfAddressListItem',
            'AddAddressResponseBody' => '\\Enesdayanc\\MasterpassGenerateKey\\StructType\\AddAddressResponseBody',
            'MaintainAddressListResponseBody' => '\\Enesdayanc\\MasterpassGenerateKey\\StructType\\MaintainAddressListResponseBody',
            'TransactionQueryResponseBody' => '\\Enesdayanc\\MasterpassGenerateKey\\StructType\\TransactionQueryResponseBody',
            'ArrayOfOrderItem' => '\\Enesdayanc\\MasterpassGenerateKey\\ArrayType\\ArrayOfOrderItem',
            'OrderItem' => '\\Enesdayanc\\MasterpassGenerateKey\\StructType\\OrderItem',
            'CustomTransactionQueryResponseBody' => '\\Enesdayanc\\MasterpassGenerateKey\\StructType\\CustomTransactionQueryResponseBody',
            'CompleteRegistrationResponseBody' => '\\Enesdayanc\\MasterpassGenerateKey\\StructType\\CompleteRegistrationResponseBody',
            'MPGAccountResponse' => '\\Enesdayanc\\MasterpassGenerateKey\\StructType\\MPGAccountResponse',
            'MPGAccountCustomField' => '\\Enesdayanc\\MasterpassGenerateKey\\StructType\\MPGAccountCustomField',
            'ExternalAccountResponse' => '\\Enesdayanc\\MasterpassGenerateKey\\StructType\\ExternalAccountResponse',
            'ExternalAccountCustomField' => '\\Enesdayanc\\MasterpassGenerateKey\\StructType\\ExternalAccountCustomField',
            'AddCardToMasterPassResponseBody' => '\\Enesdayanc\\MasterpassGenerateKey\\StructType\\AddCardToMasterPassResponseBody',
            'ConsumerRegistrationResponseBody' => '\\Enesdayanc\\MasterpassGenerateKey\\StructType\\ConsumerRegistrationResponseBody',
            'LinkAccountToClientResponseBody' => '\\Enesdayanc\\MasterpassGenerateKey\\StructType\\LinkAccountToClientResponseBody',
            'ConsumerAccountSearchResponseBody' => '\\Enesdayanc\\MasterpassGenerateKey\\StructType\\ConsumerAccountSearchResponseBody',
            'ConsumerAccount' => '\\Enesdayanc\\MasterpassGenerateKey\\StructType\\ConsumerAccount',
            'ConsumerRegistrationResponseBodyForPurchase' => '\\Enesdayanc\\MasterpassGenerateKey\\StructType\\ConsumerRegistrationResponseBodyForPurchase',
            'GetCardResponseBody' => '\\Enesdayanc\\MasterpassGenerateKey\\StructType\\GetCardResponseBody',
            'MasterpassPostbackResponseBody' => '\\Enesdayanc\\MasterpassGenerateKey\\StructType\\MasterpassPostbackResponseBody',
            'UpdateCardLockResponseBody' => '\\Enesdayanc\\MasterpassGenerateKey\\StructType\\UpdateCardLockResponseBody',
            'AuthenticateResponseBody' => '\\Enesdayanc\\MasterpassGenerateKey\\StructType\\AuthenticateResponseBody',
            'VerifyResponseBody' => '\\Enesdayanc\\MasterpassGenerateKey\\StructType\\VerifyResponseBody',
            'ChangeAuthTokenResponseBody' => '\\Enesdayanc\\MasterpassGenerateKey\\StructType\\ChangeAuthTokenResponseBody',
            'DefineAuthTokenResponseBody' => '\\Enesdayanc\\MasterpassGenerateKey\\StructType\\DefineAuthTokenResponseBody',
            'UnBlockMPinResponseBody' => '\\Enesdayanc\\MasterpassGenerateKey\\StructType\\UnBlockMPinResponseBody',
            'GenerateOTPResponseBody' => '\\Enesdayanc\\MasterpassGenerateKey\\StructType\\GenerateOTPResponseBody',
            'ValidateTransactionResponseBody' => '\\Enesdayanc\\MasterpassGenerateKey\\StructType\\ValidateTransactionResponseBody',
            'LoginResponseBody' => '\\Enesdayanc\\MasterpassGenerateKey\\StructType\\LoginResponseBody',
            'CheckMasterPassEndUserResponseBody' => '\\Enesdayanc\\MasterpassGenerateKey\\StructType\\CheckMasterPassEndUserResponseBody',
            'VerifyMpinResponseBody' => '\\Enesdayanc\\MasterpassGenerateKey\\StructType\\VerifyMpinResponseBody',
            'ForgotPasswordResponseBody' => '\\Enesdayanc\\MasterpassGenerateKey\\StructType\\ForgotPasswordResponseBody',
            'ResendOTPResponseBody' => '\\Enesdayanc\\MasterpassGenerateKey\\StructType\\ResendOTPResponseBody',
            'UpdateUserResponseBody' => '\\Enesdayanc\\MasterpassGenerateKey\\StructType\\UpdateUserResponseBody',
            'VerifyUserResponseBody' => '\\Enesdayanc\\MasterpassGenerateKey\\StructType\\VerifyUserResponseBody',
            'ResetMPinResponseBody' => '\\Enesdayanc\\MasterpassGenerateKey\\StructType\\ResetMPinResponseBody',
            'SetDefaultAddressResponseBody' => '\\Enesdayanc\\MasterpassGenerateKey\\StructType\\SetDefaultAddressResponseBody',
            'ArrayOfString1' => '\\Enesdayanc\\MasterpassGenerateKey\\ArrayType\\ArrayOfString1',
            'RedownloadListResponseBody' => '\\Enesdayanc\\MasterpassGenerateKey\\StructType\\RedownloadListResponseBody',
            'ArrayOfString' => '\\Enesdayanc\\MasterpassGenerateKey\\ArrayType\\ArrayOfString',
            'ReinitializeDukptResponseBody' => '\\Enesdayanc\\MasterpassGenerateKey\\StructType\\ReinitializeDukptResponseBody',
            'SetDefaultAccountResponseBody' => '\\Enesdayanc\\MasterpassGenerateKey\\StructType\\SetDefaultAccountResponseBody',
            'TransactionVoidResponseBody' => '\\Enesdayanc\\MasterpassGenerateKey\\StructType\\TransactionVoidResponseBody',
            'CustomTransactionVoidResponseBody' => '\\Enesdayanc\\MasterpassGenerateKey\\StructType\\CustomTransactionVoidResponseBody',
            'MerchantRegistrationResponseBody' => '\\Enesdayanc\\MasterpassGenerateKey\\StructType\\MerchantRegistrationResponseBody',
            'CustomFields' => '\\Enesdayanc\\MasterpassGenerateKey\\StructType\\CustomFields',
        );
    }
}
