<?php
/**
 * Class which returns the class map definition
 * @package
 */
class ClassMap
{
    /**
     * Returns the mapping between the WSDL Structs and generated Structs' classes
     * This array is sent to the \SoapClient when calling the WS
     * @return string[]
     */
    final public static function get()
    {
        return array(
            'GenerateKey' => '\\StructType\\GenerateKey',
            'GenerateKeyResponse' => '\\StructType\\GenerateKeyResponse',
            'GenerateKeyRequest' => '\\StructType\\GenerateKeyRequest',
            'GenerateKeyRequestBody' => '\\StructType\\GenerateKeyRequestBody',
            'GenerateKeyAdditionalFields' => '\\StructType\\GenerateKeyAdditionalFields',
            'GenerateKeyResult' => '\\StructType\\GenerateKeyResult',
            'GenerateKeyResponseBody' => '\\StructType\\GenerateKeyResponseBody',
            'RequestHeader' => '\\StructType\\RequestHeader',
            'CustomField' => '\\StructType\\CustomField',
            'ResponseHeader' => '\\StructType\\ResponseHeader',
            'ResponseBody' => '\\StructType\\ResponseBody',
            'SmsNotification' => '\\StructType\\SmsNotification',
            'MoneySendResponseBody' => '\\StructType\\MoneySendResponseBody',
            'MerchantFinancialResponseBody' => '\\StructType\\MerchantFinancialResponseBody',
            'ConsumerRewardResponseBody' => '\\StructType\\ConsumerRewardResponseBody',
            'ArrayOfRewardList' => '\\ArrayType\\ArrayOfRewardList',
            'RewardList' => '\\StructType\\RewardList',
            'ArrayOfChequeList' => '\\ArrayType\\ArrayOfChequeList',
            'ChequeList' => '\\StructType\\ChequeList',
            'ConsumerFinancialResponseBody' => '\\StructType\\ConsumerFinancialResponseBody',
            'MasterPassResponseCustomField' => '\\StructType\\MasterPassResponseCustomField',
            'ArrayOfListItem' => '\\ArrayType\\ArrayOfListItem',
            'ListItem' => '\\StructType\\ListItem',
            'AdditionalFields' => '\\StructType\\AdditionalFields',
            'CustomRewardResponseBody' => '\\StructType\\CustomRewardResponseBody',
            'RewardResponseBody' => '\\StructType\\RewardResponseBody',
            'CommitPurchaseResponseBody' => '\\StructType\\CommitPurchaseResponseBody',
            'CustomCommitPurchaseResponseBody' => '\\StructType\\CustomCommitPurchaseResponseBody',
            'ProcessPaymentResponseBody' => '\\StructType\\ProcessPaymentResponseBody',
            'PurchaseAndRegisterResponseBody' => '\\StructType\\PurchaseAndRegisterResponseBody',
            'CustomRemotePurchaseResponseBody' => '\\StructType\\CustomRemotePurchaseResponseBody',
            'DirectPurchaseResponseBody' => '\\StructType\\DirectPurchaseResponseBody',
            'OtherMerchantResponseBody' => '\\StructType\\OtherMerchantResponseBody',
            'ReversePurchaseResponseBody' => '\\StructType\\ReversePurchaseResponseBody',
            'DirectPurchaseResponseBody3DAuth' => '\\StructType\\DirectPurchaseResponseBody3DAuth',
            'CustomCommitRecurringPaymentResponseBody' => '\\StructType\\CustomCommitRecurringPaymentResponseBody',
            'CommitRecurringPaymentResponseBody' => '\\StructType\\CommitRecurringPaymentResponseBody',
            'ManageRecurringPaymentResponseBody' => '\\StructType\\ManageRecurringPaymentResponseBody',
            'MaintainListResponseBody' => '\\StructType\\MaintainListResponseBody',
            'ViewListResponseBody' => '\\StructType\\ViewListResponseBody',
            'TransactionRefundResponseBody' => '\\StructType\\TransactionRefundResponseBody',
            'CustomTransactionRefundResponseBody' => '\\StructType\\CustomTransactionRefundResponseBody',
            'ViewMPListResponseBody' => '\\StructType\\ViewMPListResponseBody',
            'ArrayOfMPListItem' => '\\ArrayType\\ArrayOfMPListItem',
            'MPListItem' => '\\StructType\\MPListItem',
            'Card' => '\\StructType\\Card',
            'Contact' => '\\StructType\\Contact',
            'AddressListItem' => '\\StructType\\AddressListItem',
            'ViewAddressListResponseBody' => '\\StructType\\ViewAddressListResponseBody',
            'ArrayOfAddressListItem' => '\\ArrayType\\ArrayOfAddressListItem',
            'AddAddressResponseBody' => '\\StructType\\AddAddressResponseBody',
            'MaintainAddressListResponseBody' => '\\StructType\\MaintainAddressListResponseBody',
            'TransactionQueryResponseBody' => '\\StructType\\TransactionQueryResponseBody',
            'ArrayOfOrderItem' => '\\ArrayType\\ArrayOfOrderItem',
            'OrderItem' => '\\StructType\\OrderItem',
            'CustomTransactionQueryResponseBody' => '\\StructType\\CustomTransactionQueryResponseBody',
            'CompleteRegistrationResponseBody' => '\\StructType\\CompleteRegistrationResponseBody',
            'MPGAccountResponse' => '\\StructType\\MPGAccountResponse',
            'MPGAccountCustomField' => '\\StructType\\MPGAccountCustomField',
            'ExternalAccountResponse' => '\\StructType\\ExternalAccountResponse',
            'ExternalAccountCustomField' => '\\StructType\\ExternalAccountCustomField',
            'AddCardToMasterPassResponseBody' => '\\StructType\\AddCardToMasterPassResponseBody',
            'ConsumerRegistrationResponseBody' => '\\StructType\\ConsumerRegistrationResponseBody',
            'LinkAccountToClientResponseBody' => '\\StructType\\LinkAccountToClientResponseBody',
            'ConsumerAccountSearchResponseBody' => '\\StructType\\ConsumerAccountSearchResponseBody',
            'ConsumerAccount' => '\\StructType\\ConsumerAccount',
            'ConsumerRegistrationResponseBodyForPurchase' => '\\StructType\\ConsumerRegistrationResponseBodyForPurchase',
            'GetCardResponseBody' => '\\StructType\\GetCardResponseBody',
            'MasterpassPostbackResponseBody' => '\\StructType\\MasterpassPostbackResponseBody',
            'UpdateCardLockResponseBody' => '\\StructType\\UpdateCardLockResponseBody',
            'AuthenticateResponseBody' => '\\StructType\\AuthenticateResponseBody',
            'VerifyResponseBody' => '\\StructType\\VerifyResponseBody',
            'ChangeAuthTokenResponseBody' => '\\StructType\\ChangeAuthTokenResponseBody',
            'DefineAuthTokenResponseBody' => '\\StructType\\DefineAuthTokenResponseBody',
            'UnBlockMPinResponseBody' => '\\StructType\\UnBlockMPinResponseBody',
            'GenerateOTPResponseBody' => '\\StructType\\GenerateOTPResponseBody',
            'ValidateTransactionResponseBody' => '\\StructType\\ValidateTransactionResponseBody',
            'LoginResponseBody' => '\\StructType\\LoginResponseBody',
            'CheckMasterPassEndUserResponseBody' => '\\StructType\\CheckMasterPassEndUserResponseBody',
            'VerifyMpinResponseBody' => '\\StructType\\VerifyMpinResponseBody',
            'ForgotPasswordResponseBody' => '\\StructType\\ForgotPasswordResponseBody',
            'ResendOTPResponseBody' => '\\StructType\\ResendOTPResponseBody',
            'UpdateUserResponseBody' => '\\StructType\\UpdateUserResponseBody',
            'VerifyUserResponseBody' => '\\StructType\\VerifyUserResponseBody',
            'ResetMPinResponseBody' => '\\StructType\\ResetMPinResponseBody',
            'SetDefaultAddressResponseBody' => '\\StructType\\SetDefaultAddressResponseBody',
            'ArrayOfString1' => '\\ArrayType\\ArrayOfString1',
            'RedownloadListResponseBody' => '\\StructType\\RedownloadListResponseBody',
            'ArrayOfString' => '\\ArrayType\\ArrayOfString',
            'ReinitializeDukptResponseBody' => '\\StructType\\ReinitializeDukptResponseBody',
            'SetDefaultAccountResponseBody' => '\\StructType\\SetDefaultAccountResponseBody',
            'TransactionVoidResponseBody' => '\\StructType\\TransactionVoidResponseBody',
            'CustomTransactionVoidResponseBody' => '\\StructType\\CustomTransactionVoidResponseBody',
            'MerchantRegistrationResponseBody' => '\\StructType\\MerchantRegistrationResponseBody',
            'CustomFields' => '\\StructType\\CustomFields',
        );
    }
}
